#springboot 通用配置文件
server:
  #设置服务器端口号
  port: 8089
spring:
  profiles:
    #采用的配置文件
    active: dev
#  mvc:
#    #静态资源访问路径
#    static-path-pattern: /resources/**
#    #注意：自定义文件上传路径会覆盖掉spring boot默认的静态资源路径，所以此处必须是把之前默认路径写上。
#    resources:
#      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  thymeleaf:
    cache: false
logging:
  #配置各个文件夹输出日志的级别
  level:
    root: info
    com.moonmagician: debug